name: RSS to Facebook Poster

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:  # Allow manual runs

jobs:
  post-updates:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run RSS Poster
      env:
        FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
        FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
      run: |
        python main.py

    - name: Commit posted_entries.txt
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add posted_entries.txt
        git commit -m "Update posted entries" || echo "No changes to commit"
        git push
