name: RSS to Facebook Poster

on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
  workflow_dispatch:

jobs:
  post-updates:
    runs-on: ubuntu-latest
    permissions:  # Add this permissions block
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: true  # Crucial for write access
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run RSS Poster
      env:
        FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}
        FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
      run: |
        python main.py

    - name: Commit and Push
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add posted_entries.txt
        
        # Use GitHub token for authentication
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update posted entries" && git push)
